spring:
  application:
    name: banking-app
    bankName: "GDC Bank"

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bgapp}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:961code@gmail.com}
    password: ${MAIL_PASSWORD:zvikjtbccdozpsty}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 50


logging:
  level:
    org.springframework.web: INFO
    com.alikhdr.bankingApp: DEBUG
    org.hibernate.SQL: INFO

ai:
  openai:
    enabled: true
    api-key: ${OPENAI_API_KEY:}
    base-url: https://api.openai.com/v1
    model: gpt-4.1-mini
    timeout-ms: 5000
    max-tokens: 300
    requests-per-minute: 30

# Circuit Breaker, to make OpenAI service calls fault-tolerant (fail-safe)
resilience4j:
  circuitbreaker:
    instances:
      openaiService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
app:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: eu-north-1
  bucketName: gdc-bank-receipts-s3

finnhub:
  api:
    key: d80f15pr01qq9ln3l7v0d80f15pr01qq9ln3l7vg

option:
  pricing:
    risk-free-rate: 0.05 # 5%
    volatility: 0.20 # 20%
